-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and CONSTRAINTs may not be valid for execution.

create table mru_dev."Category_Assigned_Products" (
  category_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  product_id bigint NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT Catagory_Assigned_Products_pkey primary key (category_id, product_id),
  CONSTRAINT Catagory_Assigned_Products_category_id_fkey FOREIGN KEY (category_id) REFERENCES mru_dev."Category_Tags" (id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT Catagory_Assigned_Products_product_id_fkey FOREIGN KEY (product_id) REFERENCES mru_dev."Product_Information" (id) ON UPDATE CASCADE ON DELETE SET NULL
) TABLESPACE pg_default;

create index IF not exists category_assigned_products_product_id_index on mru_dev."Category_Assigned_Products" using btree (product_id) TABLESPACE pg_default;

CREATE TABLE mru_dev."Category_Assigned_Products" (
  category_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  product_id bigint NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT Catagory_Assigned_Products_pkey PRIMARY KEY (category_id, product_id),
  CONSTRAINT Catagory_Assigned_Products_category_id_fkey FOREIGN KEY (category_id) REFERENCES mru_dev."Category_Tags" (id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT Catagory_Assigned_Products_product_id_fkey FOREIGN KEY (product_id) REFERENCES mru_dev."Product_Information" (id) ON UPDATE CASCADE ON DELETE SET NULL
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS category_assigned_products_product_id_index ON mru_dev."Category_Assigned_Products" USING btree (product_id) TABLESPACE pg_default;

CREATE TABLE mru_dev."Category_Tags" (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name character varying null,
  description character varying null,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT Catagory_Tags_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE TABLE mru_dev."Chats" (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id_1 uuid null DEFAULT auth.uid (),
  user_id_2 uuid null,
  visible boolean null DEFAULT true,
  CONSTRAINT Chats_pkey PRIMARY KEY (id),
  CONSTRAINT Chats_user_id_1_fkey FOREIGN KEY (user_id_1) REFERENCES mru_dev."User_Information" (supabase_id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT Chats_user_id_2_fkey FOREIGN KEY (user_id_2) REFERENCES mru_dev."User_Information" (supabase_id) ON UPDATE CASCADE ON DELETE SET NULL
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS chats_user_id_1_index ON mru_dev."Chats" USING btree (user_id_1) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS chats_user_id_2_index ON mru_dev."Chats" USING btree (user_id_2) TABLESPACE pg_default;

CREATE TABLE mru_dev."Messages" (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  chat_id bigint null,
  logged_message character varying null,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  sender_id uuid null,
  visible boolean null,
  CONSTRAINT Messages_pkey PRIMARY KEY (id),
  CONSTRAINT Messages_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES mru_dev."Chats" (id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT Messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES mru_dev."User_Information" (supabase_id) ON DELETE SET NULL
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS messages_chat_id_index ON mru_dev."Messages" USING btree (chat_id) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS messages_sender_id_index ON mru_dev."Messages" USING btree (sender_id) TABLESPACE pg_default;

CREATE TABLE mru_dev."Product_Information" (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  title character varying null,
  description character varying null,
  image jsonb null,
  price double precision null,
  stock_count bigint null,
  user_id uuid null,
  "isListed" boolean null DEFAULT false,
  "isDeleted" boolean null DEFAULT false,
  CONSTRAINT Product_Information_pkey PRIMARY KEY (id),
  CONSTRAINT Product_Information_user_id_fkey FOREIGN KEY (user_id) REFERENCES mru_dev."User_Information" (supabase_id) ON UPDATE CASCADE ON DELETE SET NULL
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS product_information_user_id_index ON mru_dev."Product_Information" USING btree (user_id) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS product_information_user_id_index ON mru_dev."Product_Information" USING btree (user_id) TABLESPACE pg_default;

CREATE TABLE mru_dev."Reports" (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  closed_date date null,
  is_closed boolean null DEFAULT false,
  linked_information character varying null,
  created_by_id uuid null DEFAULT auth.uid (),
  created_on_id uuid null,
  description character varying null,
  CONSTRAINT Reports_pkey PRIMARY KEY (id),
  CONSTRAINT Reports_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES mru_dev."User_Information" (supabase_id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT Reports_created_on_id_fkey FOREIGN KEY (created_on_id) REFERENCES mru_dev."User_Information" (supabase_id) ON UPDATE CASCADE ON DELETE SET NULL
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS reports_created_by_id_index ON mru_dev."Reports" USING btree (created_by_id) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS reports_created_on_id_index ON mru_dev."Reports" USING btree (created_on_id) TABLESPACE pg_default;

CREATE TABLE mru_dev."Reviews" (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  product_id bigint null,
  rating real null,
  description character varying null,
  created_by_id uuid null DEFAULT auth.uid (),
  created_on_id uuid null,
  CONSTRAINT Reviews_pkey PRIMARY KEY (id),
  CONSTRAINT Reviews_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES mru_dev."User_Information" (supabase_id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT Reviews_created_on_id_fkey FOREIGN KEY (created_on_id) REFERENCES mru_dev."User_Information" (supabase_id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT Reviews_product_id_fkey FOREIGN KEY (product_id) REFERENCES mru_dev."Product_Information" (id) ON UPDATE CASCADE ON DELETE SET NULL
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS reviews_created_by_id_index ON mru_dev."Reviews" USING btree (created_by_id) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS reviews_created_on_id_index ON mru_dev."Reviews" USING btree (created_on_id) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS reviews_product_id_index ON mru_dev."Reviews" USING btree (product_id) TABLESPACE pg_default;

CREATE TABLE mru_dev."User_Information" (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  first_name character varying null,
  last_name character varying null,
  email character varying null,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_on date null,
  is_deleted boolean null DEFAULT false,
  is_flagged boolean null DEFAULT false,
  flagged_type character varying null,
  user_name character varying null,
  supabase_id uuid NOT NULL DEFAULT auth.uid (),
  rating real null,
  profile_image json null,
  CONSTRAINT User_Information_pkey PRIMARY KEY (id),
  CONSTRAINT User_Information_id_key unique (id),
  CONSTRAINT User_Information_supabase_id_key unique (supabase_id),
  CONSTRAINT unique_supabase_id unique (supabase_id),
  CONSTRAINT user_information_email_key unique (email),
  CONSTRAINT User_Information_supabase_id_fkey FOREIGN KEY (supabase_id) REFERENCES auth.users (id) ON UPDATE CASCADE ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE TABLE mru_dev."User_Interactions" (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id_1 uuid null DEFAULT auth.uid (),
  user_id_2 uuid null,
  user_1_is_blocked boolean null DEFAULT false,
  user_1_is_muted boolean null DEFAULT false,
  user_2_is_blocked boolean null DEFAULT false,
  user_2_is_muted boolean null DEFAULT false,
  CONSTRAINT Blocked_Users_pkey PRIMARY KEY (id),
  CONSTRAINT unique_user_pair unique (user_id_1, user_id_2),
  CONSTRAINT User_Interactions_user_id_1_fkey FOREIGN KEY (user_id_1) REFERENCES mru_dev."User_Information" (supabase_id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT User_Interactions_user_id_2_fkey FOREIGN KEY (user_id_2) REFERENCES mru_dev."User_Information" (supabase_id) ON UPDATE CASCADE ON DELETE SET NULL
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS user_interactions_user_id_2_index ON mru_dev."User_Interactions" USING btree (user_id_2) TABLESPACE pg_default;